version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A src.main worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
