version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  redis:
    image: redis
    ports:
      - 6379:6379
  

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A src worker -l info
    ports:
      - 5678:5678


  flower:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A src flower --port=5678
    ports:
      - 5678:5678



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pg-network
    depends_on:
      - db
  

